//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceAuditWeb.BranchLocationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BranchLocationService.ILocationService")]
    public interface ILocationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/DoWork", ReplyAction="http://tempuri.org/ILocationService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/DoWork", ReplyAction="http://tempuri.org/ILocationService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/insertBranchLocation", ReplyAction="http://tempuri.org/ILocationService/insertBranchLocationResponse")]
        int insertBranchLocation(Compliance.DataObject.Branch branchlocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/insertBranchLocation", ReplyAction="http://tempuri.org/ILocationService/insertBranchLocationResponse")]
        System.Threading.Tasks.Task<int> insertBranchLocationAsync(Compliance.DataObject.Branch branchlocation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocationServiceChannel : ComplianceAuditWeb.BranchLocationService.ILocationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationServiceClient : System.ServiceModel.ClientBase<ComplianceAuditWeb.BranchLocationService.ILocationService>, ComplianceAuditWeb.BranchLocationService.ILocationService {
        
        public LocationServiceClient() {
        }
        
        public LocationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int insertBranchLocation(Compliance.DataObject.Branch branchlocation) {
            return base.Channel.insertBranchLocation(branchlocation);
        }
        
        public System.Threading.Tasks.Task<int> insertBranchLocationAsync(Compliance.DataObject.Branch branchlocation) {
            return base.Channel.insertBranchLocationAsync(branchlocation);
        }
    }
}
