//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceAuditWeb.VendorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VendorService.IVendorService")]
    public interface IVendorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorService/insertVendor", ReplyAction="http://tempuri.org/IVendorService/insertVendorResponse")]
        int insertVendor(Compliance.DataObject.VendorMaster vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorService/insertVendor", ReplyAction="http://tempuri.org/IVendorService/insertVendorResponse")]
        System.Threading.Tasks.Task<int> insertVendorAsync(Compliance.DataObject.VendorMaster vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorService/updateVendor", ReplyAction="http://tempuri.org/IVendorService/updateVendorResponse")]
        int updateVendor(Compliance.DataObject.VendorMaster vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorService/updateVendor", ReplyAction="http://tempuri.org/IVendorService/updateVendorResponse")]
        System.Threading.Tasks.Task<int> updateVendorAsync(Compliance.DataObject.VendorMaster vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorService/insertVendorForBranch", ReplyAction="http://tempuri.org/IVendorService/insertVendorForBranchResponse")]
        int insertVendorForBranch(int[] VendorID, int OrgCompanyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendorService/insertVendorForBranch", ReplyAction="http://tempuri.org/IVendorService/insertVendorForBranchResponse")]
        System.Threading.Tasks.Task<int> insertVendorForBranchAsync(int[] VendorID, int OrgCompanyID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVendorServiceChannel : ComplianceAuditWeb.VendorService.IVendorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendorServiceClient : System.ServiceModel.ClientBase<ComplianceAuditWeb.VendorService.IVendorService>, ComplianceAuditWeb.VendorService.IVendorService {
        
        public VendorServiceClient() {
        }
        
        public VendorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertVendor(Compliance.DataObject.VendorMaster vendor) {
            return base.Channel.insertVendor(vendor);
        }
        
        public System.Threading.Tasks.Task<int> insertVendorAsync(Compliance.DataObject.VendorMaster vendor) {
            return base.Channel.insertVendorAsync(vendor);
        }
        
        public int updateVendor(Compliance.DataObject.VendorMaster vendor) {
            return base.Channel.updateVendor(vendor);
        }
        
        public System.Threading.Tasks.Task<int> updateVendorAsync(Compliance.DataObject.VendorMaster vendor) {
            return base.Channel.updateVendorAsync(vendor);
        }
        
        public int insertVendorForBranch(int[] VendorID, int OrgCompanyID) {
            return base.Channel.insertVendorForBranch(VendorID, OrgCompanyID);
        }
        
        public System.Threading.Tasks.Task<int> insertVendorForBranchAsync(int[] VendorID, int OrgCompanyID) {
            return base.Channel.insertVendorForBranchAsync(VendorID, OrgCompanyID);
        }
    }
}
