//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceAuditWeb.ComplianceXrefService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComplianceXrefService.IComplianceXrefService")]
    public interface IComplianceXrefService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/insertActs", ReplyAction="http://tempuri.org/IComplianceXrefService/insertActsResponse")]
        int insertActs(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/insertActs", ReplyAction="http://tempuri.org/IComplianceXrefService/insertActsResponse")]
        System.Threading.Tasks.Task<int> insertActsAsync(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/insertRules", ReplyAction="http://tempuri.org/IComplianceXrefService/insertRulesResponse")]
        int insertRules(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/insertRules", ReplyAction="http://tempuri.org/IComplianceXrefService/insertRulesResponse")]
        System.Threading.Tasks.Task<int> insertRulesAsync(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/insertSection", ReplyAction="http://tempuri.org/IComplianceXrefService/insertSectionResponse")]
        int insertSection(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/insertSection", ReplyAction="http://tempuri.org/IComplianceXrefService/insertSectionResponse")]
        System.Threading.Tasks.Task<int> insertSectionAsync(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/UpdateActs", ReplyAction="http://tempuri.org/IComplianceXrefService/UpdateActsResponse")]
        int UpdateActs(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/UpdateActs", ReplyAction="http://tempuri.org/IComplianceXrefService/UpdateActsResponse")]
        System.Threading.Tasks.Task<int> UpdateActsAsync(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/UpdateRules", ReplyAction="http://tempuri.org/IComplianceXrefService/UpdateRulesResponse")]
        int UpdateRules(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/UpdateRules", ReplyAction="http://tempuri.org/IComplianceXrefService/UpdateRulesResponse")]
        System.Threading.Tasks.Task<int> UpdateRulesAsync(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetActs", ReplyAction="http://tempuri.org/IComplianceXrefService/GetActsResponse")]
        string GetActs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetActs", ReplyAction="http://tempuri.org/IComplianceXrefService/GetActsResponse")]
        System.Threading.Tasks.Task<string> GetActsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetSections", ReplyAction="http://tempuri.org/IComplianceXrefService/GetSectionsResponse")]
        string GetSections(int parentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetSections", ReplyAction="http://tempuri.org/IComplianceXrefService/GetSectionsResponse")]
        System.Threading.Tasks.Task<string> GetSectionsAsync(int parentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetRules", ReplyAction="http://tempuri.org/IComplianceXrefService/GetRulesResponse")]
        string GetRules(int parentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetRules", ReplyAction="http://tempuri.org/IComplianceXrefService/GetRulesResponse")]
        System.Threading.Tasks.Task<string> GetRulesAsync(int parentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetAuditorId", ReplyAction="http://tempuri.org/IComplianceXrefService/GetAuditorIdResponse")]
        int GetAuditorId(int Branchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetAuditorId", ReplyAction="http://tempuri.org/IComplianceXrefService/GetAuditorIdResponse")]
        System.Threading.Tasks.Task<int> GetAuditorIdAsync(int Branchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/getRuleforBranch", ReplyAction="http://tempuri.org/IComplianceXrefService/getRuleforBranchResponse")]
        string getRuleforBranch(int sectionid, int branchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/getRuleforBranch", ReplyAction="http://tempuri.org/IComplianceXrefService/getRuleforBranchResponse")]
        System.Threading.Tasks.Task<string> getRuleforBranchAsync(int sectionid, int branchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/inseretActandRuleforBranch", ReplyAction="http://tempuri.org/IComplianceXrefService/inseretActandRuleforBranchResponse")]
        bool inseretActandRuleforBranch(Compliance.DataObject.ComplianceAudit audit, int[] ruleid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/inseretActandRuleforBranch", ReplyAction="http://tempuri.org/IComplianceXrefService/inseretActandRuleforBranchResponse")]
        System.Threading.Tasks.Task<bool> inseretActandRuleforBranchAsync(Compliance.DataObject.ComplianceAudit audit, int[] ruleid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComplianceXrefServiceChannel : ComplianceAuditWeb.ComplianceXrefService.IComplianceXrefService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComplianceXrefServiceClient : System.ServiceModel.ClientBase<ComplianceAuditWeb.ComplianceXrefService.IComplianceXrefService>, ComplianceAuditWeb.ComplianceXrefService.IComplianceXrefService {
        
        public ComplianceXrefServiceClient() {
        }
        
        public ComplianceXrefServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComplianceXrefServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComplianceXrefServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComplianceXrefServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertActs(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.insertActs(compliance);
        }
        
        public System.Threading.Tasks.Task<int> insertActsAsync(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.insertActsAsync(compliance);
        }
        
        public int insertRules(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.insertRules(compliance);
        }
        
        public System.Threading.Tasks.Task<int> insertRulesAsync(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.insertRulesAsync(compliance);
        }
        
        public int insertSection(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.insertSection(compliance);
        }
        
        public System.Threading.Tasks.Task<int> insertSectionAsync(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.insertSectionAsync(compliance);
        }
        
        public int UpdateActs(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.UpdateActs(compliance);
        }
        
        public System.Threading.Tasks.Task<int> UpdateActsAsync(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.UpdateActsAsync(compliance);
        }
        
        public int UpdateRules(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.UpdateRules(compliance);
        }
        
        public System.Threading.Tasks.Task<int> UpdateRulesAsync(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.UpdateRulesAsync(compliance);
        }
        
        public string GetActs() {
            return base.Channel.GetActs();
        }
        
        public System.Threading.Tasks.Task<string> GetActsAsync() {
            return base.Channel.GetActsAsync();
        }
        
        public string GetSections(int parentid) {
            return base.Channel.GetSections(parentid);
        }
        
        public System.Threading.Tasks.Task<string> GetSectionsAsync(int parentid) {
            return base.Channel.GetSectionsAsync(parentid);
        }
        
        public string GetRules(int parentid) {
            return base.Channel.GetRules(parentid);
        }
        
        public System.Threading.Tasks.Task<string> GetRulesAsync(int parentid) {
            return base.Channel.GetRulesAsync(parentid);
        }
        
        public int GetAuditorId(int Branchid) {
            return base.Channel.GetAuditorId(Branchid);
        }
        
        public System.Threading.Tasks.Task<int> GetAuditorIdAsync(int Branchid) {
            return base.Channel.GetAuditorIdAsync(Branchid);
        }
        
        public string getRuleforBranch(int sectionid, int branchid) {
            return base.Channel.getRuleforBranch(sectionid, branchid);
        }
        
        public System.Threading.Tasks.Task<string> getRuleforBranchAsync(int sectionid, int branchid) {
            return base.Channel.getRuleforBranchAsync(sectionid, branchid);
        }
        
        public bool inseretActandRuleforBranch(Compliance.DataObject.ComplianceAudit audit, int[] ruleid) {
            return base.Channel.inseretActandRuleforBranch(audit, ruleid);
        }
        
        public System.Threading.Tasks.Task<bool> inseretActandRuleforBranchAsync(Compliance.DataObject.ComplianceAudit audit, int[] ruleid) {
            return base.Channel.inseretActandRuleforBranchAsync(audit, ruleid);
        }
    }
}
