//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplianceAuditWeb.ComplianceXrefService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComplianceXrefService.IComplianceXrefService")]
    public interface IComplianceXrefService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/insertActs", ReplyAction="http://tempuri.org/IComplianceXrefService/insertActsResponse")]
        bool insertActs(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/insertActs", ReplyAction="http://tempuri.org/IComplianceXrefService/insertActsResponse")]
        System.Threading.Tasks.Task<bool> insertActsAsync(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/insertRules", ReplyAction="http://tempuri.org/IComplianceXrefService/insertRulesResponse")]
        bool insertRules(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/insertRules", ReplyAction="http://tempuri.org/IComplianceXrefService/insertRulesResponse")]
        System.Threading.Tasks.Task<bool> insertRulesAsync(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/UpdateActs", ReplyAction="http://tempuri.org/IComplianceXrefService/UpdateActsResponse")]
        bool UpdateActs(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/UpdateActs", ReplyAction="http://tempuri.org/IComplianceXrefService/UpdateActsResponse")]
        System.Threading.Tasks.Task<bool> UpdateActsAsync(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/UpdateRules", ReplyAction="http://tempuri.org/IComplianceXrefService/UpdateRulesResponse")]
        bool UpdateRules(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/UpdateRules", ReplyAction="http://tempuri.org/IComplianceXrefService/UpdateRulesResponse")]
        System.Threading.Tasks.Task<bool> UpdateRulesAsync(Compliance.DataObject.ComplianceXref compliance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetActs", ReplyAction="http://tempuri.org/IComplianceXrefService/GetActsResponse")]
        string GetActs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetActs", ReplyAction="http://tempuri.org/IComplianceXrefService/GetActsResponse")]
        System.Threading.Tasks.Task<string> GetActsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetSections", ReplyAction="http://tempuri.org/IComplianceXrefService/GetSectionsResponse")]
        string GetSections();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetSections", ReplyAction="http://tempuri.org/IComplianceXrefService/GetSectionsResponse")]
        System.Threading.Tasks.Task<string> GetSectionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetRules", ReplyAction="http://tempuri.org/IComplianceXrefService/GetRulesResponse")]
        string GetRules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplianceXrefService/GetRules", ReplyAction="http://tempuri.org/IComplianceXrefService/GetRulesResponse")]
        System.Threading.Tasks.Task<string> GetRulesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComplianceXrefServiceChannel : ComplianceAuditWeb.ComplianceXrefService.IComplianceXrefService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComplianceXrefServiceClient : System.ServiceModel.ClientBase<ComplianceAuditWeb.ComplianceXrefService.IComplianceXrefService>, ComplianceAuditWeb.ComplianceXrefService.IComplianceXrefService {
        
        public ComplianceXrefServiceClient() {
        }
        
        public ComplianceXrefServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComplianceXrefServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComplianceXrefServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComplianceXrefServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool insertActs(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.insertActs(compliance);
        }
        
        public System.Threading.Tasks.Task<bool> insertActsAsync(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.insertActsAsync(compliance);
        }
        
        public bool insertRules(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.insertRules(compliance);
        }
        
        public System.Threading.Tasks.Task<bool> insertRulesAsync(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.insertRulesAsync(compliance);
        }
        
        public bool UpdateActs(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.UpdateActs(compliance);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateActsAsync(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.UpdateActsAsync(compliance);
        }
        
        public bool UpdateRules(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.UpdateRules(compliance);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRulesAsync(Compliance.DataObject.ComplianceXref compliance) {
            return base.Channel.UpdateRulesAsync(compliance);
        }
        
        public string GetActs() {
            return base.Channel.GetActs();
        }
        
        public System.Threading.Tasks.Task<string> GetActsAsync() {
            return base.Channel.GetActsAsync();
        }
        
        public string GetSections() {
            return base.Channel.GetSections();
        }
        
        public System.Threading.Tasks.Task<string> GetSectionsAsync() {
            return base.Channel.GetSectionsAsync();
        }
        
        public string GetRules() {
            return base.Channel.GetRules();
        }
        
        public System.Threading.Tasks.Task<string> GetRulesAsync() {
            return base.Channel.GetRulesAsync();
        }
    }
}
